services:
  frontend:
    image: node:18-alpine
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend
    entrypoint: sh -c "npm install && npm run dev -w frontend"

  backend:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://root:example@database:27017
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev -w backend"
    depends_on:
      - database

  database:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
